---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: 'chef'
  product_version: '14'
  chef_client_path: /usr/bin/chef-client
  multiple_converge: 2
  enforce_idempotency: true

verifier:
  name: inspec

platforms:
  - name: centos-7
  # - name: windows-2019
  #   driver_config:
  #     box: tas50/windows_2019

suites:
  - name: distributed
    named_run_list: distributed
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
  - name: supervised
    named_run_list: supervised
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
